name: Service CI

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    uses: bestdevopsengineer/framework-repo/.github/workflows/reusable-ci.yml@main

    secrets: inherit
    with:
      image_name: order-service
      delivery_mode: trunk
      java_version: "21"
      run_tests: true
